### ISSUE TITLE
contribute to Code & Supply

### ISSUE THREAD

**Issue by chadwhitacre** [whit537/whit537.org#23]
Hey @justinxreese!

Great to be back _en scene_ last week. Thanks for encouraging me to re-engage. :-)

Can we talk talks?

Do you want me for Abstractions? And/or a Code & Supply meetup? Please consider me at your disposal.

A few things I could talk about:
- **Gratipay Finances.** In consultation with a CPA, we've built [a really cool accounting system](https://github.com/gratipay/finances) using open-source tools (Ledger, GitHub, Travis, Python). We're now in the process of entering 4 years / $1,000,000+ of data into this system. We're aiming for our first audit in late summer. I could talk about the basics of accounting and describe the system we came up with.
- **Fraggles and Doozers.** Remember [_Fraggle Rock_](https://en.wikipedia.org/wiki/Fraggle_Rock)? Fraggles have a 30-minute work week. Doozers work constantly. They live together in symbiotic harmony. I could talk about how open-source points the way to a society in which everyone is enfranchised and included no matter how efficient or productive they are.
- **Abstraction.** It's funny you named the conference Abstractions ... I actually have [this whole philosophy project](http://abstract.io/n) that is based on the concept of abstraction, and I've been thinking of that as the work I'll focus on once Gratipay is established. I could talk about how the concept of abstraction unifies all of human experience.

I'd be happy to grab coffee some time to discuss these or other talk ideas. Please let me know if you think I could add value to Abstractions and/or Code & Supply! :-)

**Comment by justinxreese** [comment]
Dance your cares away.

Worries for another day.

Let the music play.

Replied via email. 

Down at Fraggle Rock.

**Comment by chadwhitacre** [comment]
Thanks, @justinxreese. :-)

To summarize here: I've filled out the C&S [form](http://www.codeandsupply.co/speakers), and we're dialing in on lunch next week to discuss further.

**Comment by chadwhitacre** [comment]
> I think all of these are great. [] will help schedule your talks. 
> 
> Since there are three, I'd like to space them out or maybe take 2 and leave one for later. Any preference on your end, Chad?

---

> Thanks, Justin. Can we start with the Finances one and go from there? I think it's the most practical.

**Comment by chadwhitacre** [comment]
> Yeah. Let's do that and Fraggle because I want more Fraggle Rock references

---

> Okay, can we talk about Fraggle next week at lunch? Need to flesh that out more. :)

**Comment by chadwhitacre** [comment]
> Sounds good!

**Comment by chadwhitacre** [comment]
Closing in favor of https://github.com/gratipay/inside.gratipay.com/issues/556.
